"""
Vector Database Collection domain models.

This module defines the domain models for managing vector database collection
configurations, including embedding models and chunking parameters.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class VectorDBCollection(BaseModel):
    """Configuration for a vector database collection.

    This model represents the configuration for how documents should be
    processed and stored in a vector database collection.
    """

    id: str = Field(
        description="Unique identifier for the vector DB collection configuration"
    )
    description: Optional[str] = Field(
        default=None, description="Description of the configuration"
    )

    # Embedding model configuration
    embedding_model_provider_id: str = Field(
        description="ID of the model provider for embedding generation"
    )
    embedding_model_name: str = Field(
        description="Name of the specific embedding model to use"
    )
    vector_dimension: int = Field(
        description="Dimension of the vector embeddings generated by the model",
        ge=1,
        le=4096,
    )

    # Vector database collection name
    collection_name: str = Field(description="Name of the vector database collection")

    # Metadata
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When the configuration was created",
    )
    created_by: str = Field(description="User ID who created this configuration")

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}


class VectorDBCollectionCreate(BaseModel):
    """Model for creating a new vector database collection configuration."""

    description: Optional[str] = Field(
        default=None, description="Description of the configuration"
    )
    embedding_model_provider_id: str = Field(
        description="ID of the model provider for embedding generation"
    )
    embedding_model_name: str = Field(
        description="Name of the specific embedding model to use"
    )
    vector_dimension: int = Field(
        description="Dimension of the vector embeddings generated by the model",
        ge=1,
        le=4096,
    )
    collection_name: str = Field(description="Name of the vector database collection")


# Use the same model for both create and update
VectorDBCollectionUpdate = VectorDBCollectionCreate
