"""
Milvus Client Usage Examples.

This module provides examples of how to use the MilvusClientWrapper
for common vector database operations.
"""

from typing import Any, Dict, List

from loguru import logger
from pydantic import BaseModel

from .client import MilvusClientWrapper
from .utils import (
    build_filter_expression,
    create_document_collection_schema,
    parse_search_results,
    prepare_document_data,
)


class DocumentModel(BaseModel):
    """Example document model for Milvus operations."""

    id: str
    page_content: str
    source_url: str = ""
    title: str = ""
    chunk_id: str = ""
    chunk_index: int = 0
    total_chunks: int = 1
    entities: List[str] = []
    relationships: List[str] = []
    tags: List[str] = []


def example_basic_usage():
    """Example of basic Milvus operations."""
    logger.info("Starting Milvus basic usage example")

    # Initialize client
    with MilvusClientWrapper(
        model=DocumentModel, collection_name="example_documents", vector_dimension=1536
    ) as milvus_client:

        # Example documents
        documents = [
            DocumentModel(
                id="doc1",
                page_content="This is the first document about machine learning.",
                source_url="https://example.com/doc1",
                title="ML Introduction",
            ),
            DocumentModel(
                id="doc2",
                page_content="This is the second document about deep learning.",
                source_url="https://example.com/doc2",
                title="Deep Learning Basics",
            ),
        ]

        # Example vectors (normally generated by embedding service)
        vectors = [
            [0.1] * 1536,  # Placeholder vector for doc1
            [0.2] * 1536,  # Placeholder vector for doc2
        ]

        # Ingest documents
        milvus_client.ingest_documents(documents, vectors)
        logger.info("Documents ingested successfully")

        # Search with vector
        query_vector = [0.15] * 1536  # Placeholder query vector
        results = milvus_client.search_with_vector(query_vector=query_vector, limit=5)

        logger.info(f"Search returned {len(results)} results")
        for result in results:
            logger.info(f"Result: {result['id']} - Score: {result['score']:.4f}")

        # Get collection count
        count = milvus_client.get_collection_count()
        logger.info(f"Collection contains {count} documents")


def example_advanced_search():
    """Example of advanced search operations with filters."""
    logger.info("Starting Milvus advanced search example")

    with MilvusClientWrapper(
        model=DocumentModel, collection_name="example_documents", vector_dimension=1536
    ) as milvus_client:

        # Build filter expression
        filters = {"chunk_index": {"$gte": 0, "$lt": 5}}
        filter_expr = build_filter_expression(filters)
        logger.info(f"Filter expression: {filter_expr}")

        # Search with filters
        query_vector = [0.1] * 1536
        results = milvus_client.search_with_vector(
            query_vector=query_vector,
            limit=10,
            filter_expr=filter_expr,
            return_fields=["id", "text", "title"],
        )

        logger.info(f"Filtered search returned {len(results)} results")
        for result in results:
            logger.info(f"Result: {result['id']}")


def example_batch_operations():
    """Example of batch operations for large datasets."""
    logger.info("Starting Milvus batch operations example")

    from .utils import batch_insert_data, get_optimal_batch_size

    # Calculate optimal batch size
    optimal_batch_size = get_optimal_batch_size(
        vector_dim=1536, available_memory_gb=4.0
    )
    logger.info(f"Optimal batch size: {optimal_batch_size}")

    with MilvusClientWrapper(
        model=DocumentModel, collection_name="example_documents", vector_dimension=1536
    ) as milvus_client:

        # Generate example data
        documents = []
        vectors = []

        for i in range(1000):  # Create 1000 example documents
            doc = DocumentModel(
                id=f"batch_doc_{i}",
                page_content=f"This is document number {i} with some content.",
                source_url=f"https://example.com/doc_{i}",
                title=f"Document {i}",
            )
            documents.append(doc)
            vectors.append([float(i % 100) / 100.0] * 1536)  # Simple vector pattern

        # Batch the data
        doc_batches = batch_insert_data(documents, optimal_batch_size)
        vector_batches = batch_insert_data(vectors, optimal_batch_size)

        # Insert in batches
        for i, (doc_batch, vector_batch) in enumerate(zip(doc_batches, vector_batches)):
            milvus_client.ingest_documents(doc_batch, vector_batch)
            logger.info(f"Inserted batch {i + 1}/{len(doc_batches)}")

        # Verify insertion
        count = milvus_client.get_collection_count()
        logger.info(f"Total documents in collection: {count}")


def example_index_management():
    """Example of index management operations."""
    logger.info("Starting Milvus index management example")

    from .indexes import MilvusIndex

    with MilvusClientWrapper(
        model=DocumentModel, collection_name="example_documents", vector_dimension=1536
    ) as milvus_client:

        # Create index manager
        index_manager = MilvusIndex(milvus_client)

        # List existing indexes
        indexes = index_manager.list_indexes()
        logger.info(f"Existing indexes: {indexes}")

        # Create additional indexes if needed
        try:
            index_manager.create_scalar_index("title")
            logger.info("Created scalar indexes for title field")
        except Exception as e:
            logger.warning(f"Index creation failed (may already exist): {e}")

        # Get index statistics
        stats = index_manager.get_index_stats()
        logger.info(f"Index statistics: {stats}")


if __name__ == "__main__":
    """Run examples if this file is executed directly."""
    try:
        example_basic_usage()
        example_advanced_search()
        example_batch_operations()
        example_index_management()
        logger.info("All examples completed successfully")
    except Exception as e:
        logger.error(f"Example failed: {e}")
        raise
